new_apps/skeetersbaseballclub/config/routes.rb
Skeetersbaseballclub::Application.routes.draw do
  
  get 'teams/:id/dashboard' => "teams#dashboard"
  get 'teams/:id/team-news', to: 'teams#team_news'
  resources :teams do
    resources :posts
    resources :events
    resources :profiles
  end

  resources :posts
  
  

  get "team-info" => 'pages#team_info', as: "info"

  get "member/dashboard"
  get "admin/dashboard"
  get "admin/schedule"
  get "admin/roster"
  get "team-portal" => "pages#team_portal"
  get "main" => "pages#main"

  devise_for :users, controllers: { invitations: "invitations"}
  
 

  resources :users
  get "sample" => "pages#sample"
  get "dashboard" => "pages#dashboard"
  get "roster" => "pages#roster"
  get "schedule" => "pages#schedule"
  get "pages/home"
  get "pages/sponsors"

  root 'pages#home'

  

end

new_apps/skeetersbaseballclub/app/models/event.rb
class Event < ActiveRecord::Base

	belongs_to :team
	
end

new_apps/skeetersbaseballclub/app/models/game.rb
class Game < ActiveRecord::Base

	belongs_to :user
end

new_apps/skeetersbaseballclub/app/models/membership.rb
class Membership < ActiveRecord::Base

	belongs_to :user
	belongs_to :team
	
end

new_apps/skeetersbaseballclub/app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	belongs_to :team

end

new_apps/skeetersbaseballclub/app/models/practice.rb
class Practice < ActiveRecord::Base

	belongs_to :user
end

new_apps/skeetersbaseballclub/app/models/profile.rb
class Profile < ActiveRecord::Base

	mount_uploader :image, ImageUploader
	belongs_to :team

end

new_apps/skeetersbaseballclub/app/models/team.rb
class Team < ActiveRecord::Base

	extend FriendlyId
	friendly_id :name, use: :slugged

	has_many :posts
	has_many :events
	has_many :profiles


end

new_apps/skeetersbaseballclub/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  
  after_create :set_super_admin


  has_many :posts
  has_many :events

  

  

  private

  def full_name
    "#{first_name} #{last_name}"
  end

  def set_super_admin
  	if User.count == 1
  		User.first.update_attribute(:super_admin, true)
  	else
  		return true
  	end
  end

end

new_apps/skeetersbaseballclub/app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
	before_filter :authorize_admin

  def dashboard
  	@post = current_user.posts.build
  	@posts = Post.order("publish_on DESC")
    @dashboard_event_list = Event.order("date asc")


  	@game = current_user.games.build
  	@practice = current_user.practices.build
    @admin_users = User.where('admin = ?', true)
  end

  def schedule
  	@game = current_user.games.build
  	@practice = current_user.practices.build
    @event = current_user.events.build
    @event_list = Event.order("created_at asc")
  end

  def roster
    @profile = Profile.new
    @profile_list = Profile.order("player_number asc")
  end

private

  def authorize_admin
    redirect_to root_path unless current_user.present?
  end


  
  
end

new_apps/skeetersbaseballclub/app/helpers/admin_helper.rb
module AdminHelper
end

new_apps/skeetersbaseballclub/app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def is_active?(link_path)
  	if current_page?(link_path)
  		"active"
  	else
			""
		end  
	end

  def markdown(content)
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true, fenced_code_blocks: true)
    @markdown.render(content).html_safe
  end

end

new_apps/skeetersbaseballclub/app/helpers/events_helper.rb
module EventsHelper
end

new_apps/skeetersbaseballclub/app/helpers/games_helper.rb
module GamesHelper
end

new_apps/skeetersbaseballclub/app/helpers/member_helper.rb
module MemberHelper
end

new_apps/skeetersbaseballclub/app/helpers/pages_helper.rb
module PagesHelper
end

new_apps/skeetersbaseballclub/app/helpers/posts_helper.rb
module PostsHelper
end

new_apps/skeetersbaseballclub/app/helpers/practices_helper.rb
module PracticesHelper
end

new_apps/skeetersbaseballclub/app/helpers/profiles_helper.rb
module ProfilesHelper
end

new_apps/skeetersbaseballclub/app/helpers/sessions_helper.rb
module SessionsHelper
end

new_apps/skeetersbaseballclub/app/helpers/teams_helper.rb
module TeamsHelper
end

new_apps/skeetersbaseballclub/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skeetersbaseballclub</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Sonsie+One' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>

</head>
<body>


<%= yield %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</body>
</html>

new_apps/skeetersbaseballclub/app/views/pages/_public_posts.html.erb
<% for post in @public_posts %>
	<div class="public-post-container">
		<h3 class="public-post-title"><%= post.title %></h3>
		<h5 class="public-post-details">
			Posted on <%= post.publish_on.strftime("%B %-d, %Y") %> |  
			By: <%= "#{post.user.first_name} #{post.user.last_name}" %>
		</h5>
		<%= markdown(post.body) %>
		<% if user_signed_in? && current_user.super_admin? == true %>
		<p class="public-post-footer">
			<%= link_to root_path, class: "btn btn-primary btn-sm" do %>
				EDIT POST
			<% end %>
		</p>
		<% end %>
	</div>
<% end %>

new_apps/skeetersbaseballclub/app/views/pages/dashboard.html.erb
<% if user_signed_in? %>
<div class="dashboard-box">
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<div class="dashboard-header">
				<%= render 'partials/admin_dashboard_header' %>
			</div>
		</div>
	</div>
</div>



<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<div class="row">
				<div class="col-md-11">
					<h1 class="dashboard-team-name">8U Skeeters</h1>
				</div>
				<div class="col-md-1">
					
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<%= render "admin/dashboard_main_menu" %>
			<div class="tab-content">
				<%= render "admin/upcoming_events" %>
			</div>
		</div>
	</div>
</div>
</div>
<% else %>
<h1 class="login-pg-text">Skeeters Baseball Club</h1>
<p class="text-center"><%= image_tag "skeeter_bw.png" %></p>
<div class="container">
	<div class="row">
		<div class="col-md-12 text-center">
			<div class="login-form-box">
				<%= form_for(resource, :as => resource_name, html: {class: "form-inline-login"}, :url => session_path(resource_name)) do |f| %>
					<div class="form-group">
						<label class="sr-only" for="exampleInputEmail2">Email address</label>
						<%= f.email_field :email, :autofocus => true, class: "form-control input-lg", id: "dark-input", placeholder: "Enter email", autocomplete: "off" %>
					</div>
					<div class="form-group">
						<label class="sr-only" for="exampleInputPassword2">Password</label>
						<%= f.password_field :password, class: "form-control input-lg", id: "dark-input", placeholder: "Password", autocomplete: "off" %>
					</div>
					<%= f.submit "Sign In", class: "btn-secondary btn-primary btn-lg-secondary" %>
				<% end %>
				<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
 					<p><%= link_to "Forgot your password?", new_password_path(resource_name) %></p>
				<% end -%>
				<p class="text-center"><%= link_to "Continue as guest", root_path,class: "btn-secondary btn-default btn-lg-secondary" %></p>
			</div>
		</div>
	</div>
</div>



<% end %>

new_apps/skeetersbaseballclub/app/views/pages/home.html.erb
<%= render 'partials/header' %>
<div class="top-container">
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<div class="row">
				<div class="col-md-7">
					
					<!-- BOOTSTRAP SLIDE -->
					<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  					<!-- Indicators -->
  					<ol class="carousel-indicators">
    					<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    					<li data-target="#carousel-example-generic" data-slide-to="1"></li>
   						<li data-target="#carousel-example-generic" data-slide-to="2"></li>
  					</ol>

  					<!-- Wrapper for slides -->
  					<div class="carousel-inner">
    					<div class="item active">
      					<%= image_tag "skeeter_home.jpg", alt: "" %>
      					<div class="carousel-caption">
        					
      					</div>
    					</div>
    					<div class="item">
    						<%= link_to image_tag("bridgemore_900.jpg", alt: ""), "http://google.com", target: "_blank" %>
    						
    					</div>
  					</div>

  					<!-- Controls -->
  					<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    				<span class="glyphicon glyphicon-chevron-left"></span>
  					</a>
  					<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    				<span class="glyphicon glyphicon-chevron-right"></span>
  					</a>
					</div>
					<!-- BOOTSTRAP SLIDE END -->
				</div>
				<div class="col-md-5">
					<h3 class="welcome-title">Welcome to Skeeters Baseball</h3>
					<p class="welcome-text">Lorem ipsum dolor sit amet, eum prima convenire theophrastus eu, nec doctus molestie eu, te duis cotidieque mea. Duo erant nihil alterum no, luptatum recteque postulant mel ad. An mel animal definitiones. In ornatus adipiscing omittantur eos, detracto insolens id pri. Amet oratio nec te, cu quo solum audiam officiis, accusata platonem ut qui.</p>
					<p><%= link_to "Read more", "#", class: "btn btn-primary btn-sm" %></p>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
<div class="sub-container">
	<div class="container">
		<div class="row">
			<div class="col-md-offset-1 col-md-10">
				<div class="row">
					<div class="col-md-7">
						<h3 class="home-sub">Updates</h3>
						<%= render "public_posts" %>
					</div>
					<div class="col-md-5">
						<h3 class="home-sub">Our Sponsors </h3>
						<div class="row">
							<div class="col-md-12">
								<div class="sponsor-placeholder">
									<%= image_tag "bridgemore_600.jpg", class: "w100" %>
								</div>
							</div>
							<div class="col-md-6">
								<div class="sponsor-placeholder"></div>
							</div>
							<div class="col-md-6">
								<div class="sponsor-placeholder"></div>
							</div>
						<div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<h3><%= link_to "Sigm Up", new_user_registration_path %></h3>

new_apps/skeetersbaseballclub/app/views/pages/roster.html.erb
<% if user_signed_in? %>
<div class="dashboard-box">
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<div class="dashboard-header">
				<%= render 'partials/admin_dashboard_header' %>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<div class="row">
				<div class="col-md-11">
					<h1 class="dashboard-team-name">8U Skeeters</h1>
				</div>
				<div class="col-md-1">
					
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<%= render "admin/dashboard_main_menu" %>
			<div class="tab-content">
				<%= render "admin/roster" %>
			</div>
		</div>
	</div>
</div>
</div>
<% else %>
<h1 class="login-pg-text">Skeeters Baseball Club</h1>
<p class="text-center"><%= image_tag "skeeter_bw.png" %></p>
<div class="container">
	<div class="row">
		<div class="col-md-12 text-center">
			<div class="login-form-box">
				<%= form_for(resource, :as => resource_name, html: {class: "form-inline-login"}, :url => session_path(resource_name)) do |f| %>
					<div class="form-group">
						<label class="sr-only" for="exampleInputEmail2">Email address</label>
						<%= f.email_field :email, :autofocus => true, class: "form-control input-lg", id: "dark-input", placeholder: "Enter email", autocomplete: "off" %>
					</div>
					<div class="form-group">
						<label class="sr-only" for="exampleInputPassword2">Password</label>
						<%= f.password_field :password, class: "form-control input-lg", id: "dark-input", placeholder: "Password", autocomplete: "off" %>
					</div>
					<%= f.submit "Sign In", class: "btn-secondary btn-primary btn-lg-secondary" %>
				<% end %>
				<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
 					<p><%= link_to "Forgot your password?", new_password_path(resource_name) %></p>
				<% end -%>
				<p class="text-center"><%= link_to "Continue as guest", root_path,class: "btn-secondary btn-default btn-lg-secondary" %></p>
			</div>
		</div>
	</div>
</div>
<% end %>

new_apps/skeetersbaseballclub/app/views/pages/sample.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<div class="dashboard-header">
				<%= render 'partials/admin_dashboard_header' %>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">

	<div class="page-wrap">

			<div class="row">
				<div class="col-md-11">
					<h1 class="dashboard-team-name">8U Skeeters</h1>
				</div>
				<div class="col-md-1">
					
				</div>
			</div>

			<%= render "admin/dashboard_main_menu" %>
			<div class="tab-content">
				<%= render "admin/upcoming_events" %>
			</div>


	</div>

		</div>
	</div>
</div>

new_apps/skeetersbaseballclub/app/views/pages/schedule.html.erb
<% if user_signed_in? %>
<div class="dashboard-box">
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<div class="dashboard-header">
				<%= render 'partials/admin_dashboard_header' %>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<div class="row">
				<div class="col-md-11">
					<h1 class="dashboard-team-name">8U Skeeters</h1>
				</div>
				<div class="col-md-1">
					
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10">
			<%= render "admin/dashboard_main_menu" %>
			<div class="tab-content">
				<%= render "admin/schedule" %>
			</div>
		</div>
	</div>
</div>
</div>
<% else %>
<h1 class="login-pg-text">Skeeters Baseball Club</h1>
<p class="text-center"><%= image_tag "skeeter_bw.png" %></p>
<div class="container">
	<div class="row">
		<div class="col-md-12 text-center">
			<div class="login-form-box">
				<%= form_for(resource, :as => resource_name, html: {class: "form-inline-login"}, :url => session_path(resource_name)) do |f| %>
					<div class="form-group">
						<label class="sr-only" for="exampleInputEmail2">Email address</label>
						<%= f.email_field :email, :autofocus => true, class: "form-control input-lg", id: "dark-input", placeholder: "Enter email", autocomplete: "off" %>
					</div>
					<div class="form-group">
						<label class="sr-only" for="exampleInputPassword2">Password</label>
						<%= f.password_field :password, class: "form-control input-lg", id: "dark-input", placeholder: "Password", autocomplete: "off" %>
					</div>
					<%= f.submit "Sign In", class: "btn-secondary btn-primary btn-lg-secondary" %>
				<% end %>
				<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
 					<p><%= link_to "Forgot your password?", new_password_path(resource_name) %></p>
				<% end -%>
				<p class="text-center"><%= link_to "Continue as guest", root_path,class: "btn-secondary btn-default btn-lg-secondary" %></p>
			</div>
		</div>
	</div>
</div>
<% end %>

new_apps/skeetersbaseballclub/app/views/pages/team-portal.html.erb
<h1 class="login-pg-text">Skeeters Baseball Club</h1>
<p class="text-center"><%= image_tag "skeeter_bw.png" %></p>
<div class="container">
	<div class="row">
		<div class="col-md-12 text-center">
			<div class="login-form-box">
				<%= form_for(resource, :as => resource_name, html: {class: "form-inline-login"}, :url => session_path(resource_name)) do |f| %>
					<div class="form-group">
						<label class="sr-only" for="exampleInputEmail2">Email address</label>
						<%= f.email_field :email, :autofocus => true, class: "form-control input-lg", id: "dark-input", placeholder: "Enter email", autocomplete: "off" %>
					</div>
					<div class="form-group">
						<label class="sr-only" for="exampleInputPassword2">Password</label>
						<%= f.password_field :password, class: "form-control input-lg", id: "dark-input", placeholder: "Password", autocomplete: "off" %>
					</div>
					<%= f.submit "Sign In", class: "btn-secondary btn-primary btn-lg-secondary", name: "set_user" %>
				
				<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
 					<p><%= link_to "Forgot your password?", new_password_path(resource_name) %></p>
				<% end -%>
				<% end %>
	<%= link_to "Continue as guest", root_path, class: "btn-secondary btn-default btn-secondary", name: "save_as_guest", id: "set_user" %></p>
			</div>
		</div>
	</div>
</div>

new_apps/skeetersbaseballclub/app/views/pages/team_info.html.erb
<%= render 'partials/header' %>
<div class="secondary-top-container">
	<div class="container">
		<div class="row">
			<div class="col-md-offset-1 col-md-10">
				<h2> </h2>
			</div>
		</div>
	</div>
</div>

new_apps/skeetersbaseballclub/app/views/pages/team_portal.html.erb
<div id="portal-wrap">
<h1 class="login-pg-text">Skeeters Baseball Club</h1>
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<p class="text-center"><%= image_tag "skeeter_bw.png" %></p>
		</div>
		<div class="col-md-6">
			<div class="team-options-container">
				<h2>Select a Team</h2>
				<% for team in @teams %>
				<!--<div class="team-options">
					<h3>Team Name</h3>
				</div> -->
				<%= link_to team.name, team, class: "team-portal-link" %>

				<% end %>
			</div>
		</div>
	</div>
</div>
</div>

new_apps/skeetersbaseballclub/app/views/partials/_admin_dashboard_header.html.erb
	<nav class="navbar navbar-dash" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <!--<a class="navbar-brand" href="#">Skeeters Baseball Club</a>-->
    <%= link_to "Skeeters Baseball Club", root_path, class: "dash-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "Teams", "#" %></li>
      
    </ul>
    <!-- 
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  	-->
    <ul class="nav navbar-nav navbar-right">
      
      
      
      <li><%= link_to "Logged in as #{current_user.first_name} #{current_user.last_name}", new_user_session_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

new_apps/skeetersbaseballclub/app/views/partials/_header.html.erb
<div class="header-container">
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <!--<a class="navbar-brand" href="#">Skeeters Baseball Club</a>-->
    <%= link_to "Skeeters Baseball Club", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
      <li><%= link_to "Team Info", info_path %></li>
      
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Teams <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% if @header_team_list.present? %>
          <% for team in @header_team_list %>
          <li><%= link_to team.name, team %></li>
          <% end %>
          <% end %>
        </ul>
      </li>
      <% end %>
      <!--<li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>-->
    </ul>
    <!--
    <form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
  	-->
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Logged in as <%= "#{current_user.first_name} #{current_user.last_name}" %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% if @header_team_list.present? %>
          <% for team in @header_team_list %>
          <li><%= link_to team.name, team %></li>
          <% end %>
          <% end %>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
      <% else %>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Member Login <b class="caret"></b></a>
        <ul class="dropdown-menu">
        	<div class="home-login-container">
        		<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
              <div class="form-group">
                <label class="sr-only">Email</label>
                <%= f.email_field :email, autofocus: true, placeholder: "Email", class: "form-control", autocomplete: :off, id: "dark-input" %>
              </div>
              <div class="form-group">
                <label class="sr-only">Password</label>
                <%= f.password_field :password, placeholder: "Password", class: "form-control", autocomplete: :off, id: "dark-input" %>
              </div>
              
              <div class="form-group">
              <%= f.submit "Sign in", class: "btn btn-primary btn-block" %>
              </div>
            <% end %>
            <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
            <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
            <% end -%>
        	</div>
        </ul>
      </li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
</div>