bogoapp/config/routes.rb
Bogoapp::Application.routes.draw do

  resources :blogs

  

  resources :administrators

  resources :categories

  
  

  match "posts/category" => "posts#category"
  resources :posts

  resources :links

  resources :lists do
    resources :items
  end
  

  resources :transactions

  resources :notes
  match "tutorials", to: "pages#tutorials", as: "tutorials"
  match "terms-of-service", to: "pages#terms_of_service", as: "terms"
  get "pages/sign_in"
  match 'sign-in', to: 'pages#sign_in', as: 'sign_in'
  get "pages/home_alt"
  get "users/show"

  match 'sign-up', to: 'identities#new', as: 'new_account'
  resources :identities

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  

  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end
  root to: "pages#home"
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  mount RedactorRails::Engine => '/redactor_rails'

end

bogoapp/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

bogoapp/app/models/administrator.rb
class Administrator < ActiveRecord::Base
  attr_accessible :name

end

bogoapp/app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :name

  has_many :posts
end

bogoapp/app/models/categorization.rb
class Categorization < ActiveRecord::Base
  attr_accessible :category_id, :post_id

  belongs_to :post
  belongs_to :category
end

bogoapp/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :categorizations
  has_many :posts, through: :categorizations

  validates_presence_of :name
  validates_uniqueness_of :name
  
end

bogoapp/app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  attr_accessible :email, :name, :password, :password_confirmation#, :password_digest
  
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i

end

bogoapp/app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :completed, :list_id, :name

  belongs_to :list

end

bogoapp/app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :link_name, :link_url, :user_id

  belongs_to :user
end

bogoapp/app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :user_id

  belongs_to :user
  has_many :items

  
end

bogoapp/app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :content, :user_id

  belongs_to :user
  validates_presence_of :content

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", 
          user_id: user.id)
  end
end

bogoapp/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :publish_on, :published, :status, :title, :category_ids, :author, :blog_id

  has_many :categorizations
  has_many :categories, through: :categorizations
  accepts_nested_attributes_for :categorizations
  belongs_to :blog

  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :body
  validates_presence_of :status

  def self.search(search)
  	if search
  		find(:all, conditions: ['title || body LIKE ?', "%#{search}%"])
  	else
  		find(:all)
  	end
  end
end

bogoapp/app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

bogoapp/app/models/transaction.rb
class Transaction < ActiveRecord::Base
  attr_accessible :date, :saved, :spent

  belongs_to :user

  def average_savings_per_transaction
  	total = self.spent + self.saved
  	average = self.saved / total * 100
  end

  
end

bogoapp/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid
  attr_accessor :password

  has_many :links
  has_many :lists
  has_many :transactions
  has_many :notes
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  def following?(other_user)
  	relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
  	relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
  	relationships.find_by_followed_id(other_user.id).destroy
  end	

  def feed
    Note.from_users_followed_by(self)
  end


  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at) unless auth.credentials.expires_at.nil?
      user.save!
    end
  end
end

bogoapp/app/helpers/blogs_helper.rb
module BlogsHelper
end

bogoapp/app/helpers/items_helper.rb
module ItemsHelper
end

bogoapp/app/helpers/links_helper.rb
module LinksHelper
end

bogoapp/app/helpers/lists_helper.rb
module ListsHelper
end

bogoapp/app/helpers/notes_helper.rb
module NotesHelper
end

bogoapp/app/helpers/users_helper.rb
module UsersHelper
end

bogoapp/app/views/pages/_header_logged_in.html.erb
<div class="alt-header">
  <div class="row-fluid">
    <div class="span6">
      <ul class="inline header-nav">
        <li><h4 class="logo">BOGO<span class="white">FY</span></h4></li>
        <li>
          <%= link_to(root_path, class: "header-link") do %>
            <i class="icon-home icon-large"></i>
          <% end %>
        </li>
        <li><h4><%= link_to "Tour", root_path, class: "header-link" %></h4></li>
        <li><h4><%= link_to "Blog", posts_path, class: "header-link" %></h4></li>
        <li><h4><%= link_to "Tutorials", root_path, class: "header-link" %></h4></li>
      </ul>
    </div>
    <div class="span6">
      <ul class="inline header-nav pull-right">
        <li>
          <%= link_to(root_path, class: "header-link") do %>
            <i class="icon-user icon-large"></i>
          <% end %>
        </li>
       
        <li><h4><%= link_to "Logout", signout_path, class: "green-link" %></h4></li>
      </ul>
      
    </div>
  </div>
</div>

bogoapp/app/views/pages/_header_logged_out.html.erb
<div class="alt-header">
  <div class="row-fluid">
    <div class="span6">
      <ul class="inline header-nav">
        <li><h4 class="logo">BOGO<span class="white">FY</span></h4></li>
        <li><h4><%= link_to "Tour", root_path, class: "header-link" %></h4></li>
        <li><h4><%= link_to "Blog", posts_path, class: "header-link" %></h4></li>
        <li><h4><%= link_to "Tutorials", root_path, class: "header-link" %></h4></li>
      </ul>
    </div>
    <div class="span6">
      <h4 class="white pull-right light">
        <ul class="inline">
          <li><%= link_to "Sign Up", new_account_path, class: "green-link" %></li>
          <!--<li class="divider-vertical"></li>-->
          <li><span class="green">|</span></li>
          <li class="dropdown arrow-right-signin">
            <%= link_to "Sign In", "#", data: { toggle: "dropdown" }, class: "green-link" %>
            <strong class="caret"></strong>
            <div class="dropdown-menu", style="margin-top:22px;">
              <div class="dropdown-signin">
                <!-- Sign in Form -->
                <%= form_tag "/auth/identity/callback", autocomplete: "off" do %>
                  <div class="list-input">
                    <label>Email</label>
                    <%= text_field_tag :auth_key %>
                  </div>
                  <div class="list-input">
                    <label>Password</label>
                    <%= password_field_tag :password %>
                  </div>
                  <div class="submit-container">
                    <%= submit_tag "Login", class: "note-green-btn-signin btn-block" %>
                    <p class="or">or</p>
                    <%= link_to "Sign in with Facebook", "/auth/facebook", class: "signin-fb-btn btn-block" %>
                  </div>
                  
                <% end %>
            </div>
          </li>
        </ul>
        
      </h4>
    </div>
  </div>
</div>

bogoapp/app/views/pages/_home_main.html.erb
<div class="side-box-container">
  <div class="box-header">
    <p class="box-header-text">Recent Transactions | <%= link_to "View all", transactions_path %></p>
  </div>

      <h4 id="add-transaction-link">Add Transaction</h4>
      <div class="transaction-form-container">
        <br>
        
        <%= form_for @transaction, html: {class: "form-inline"} do |f| %>
          <div class="input-prepend">
          <span class="add-on"><i class="icon-calendar"></i></span>
          <%= f.text_field :date, id: "datepicker", class: "input-small", placeholder: "Date" %>
          </div>
          <div class="input-prepend">
            <span class="add-on">$</span>
            <%= f.text_field :spent, placeholder: "Spent", class: "input-small" %>
          </div>
          <div class="input-prepend">
            <span class="add-on">$</span>
            <%= f.text_field :saved, placeholder: "Saved", class: "input-small" %>
          </div>
          <%= f.submit "Submit", class: "btn" %>
        <% end %>
      </div>
      <div class="transaction-list-container">
      <% for transaction in @recent_transactions %>
        <p>You spent <%=  transaction.spent %> and saved <%= transaction.saved %> on <%= transaction.date.strftime("%b %-d, %Y") %> saving <%= number_to_percentage transaction.average_savings_per_transaction %>.</p>
      <% end %>
      </div>
</div>
<div class="side-box-container">
  <div class="box-header">
    <p class="box-header-text">Recent Activity</p>
  </div>
      <% for note in @home_feed %>
      <div class="note-container">
        <div class="row-fluid">
          <div class="span6">
            <p class="note-name"><%= link_to note.user.name %></p>
          </div>
          <div class="span6">
            <p class="note-time pull-right"><%= time_ago_in_words(note.created_at) %></p>
          </div>
        </div>
        <p><%= note.content %></p>
      </div>
      <% end %>
    </div>

bogoapp/app/views/pages/_home_side.html.erb
<div class="hm-side-container">
  <div class="side-box-container">
    <div class="box-header">
    <p class="box-header-text">My Profile</p>
  </div>
  <div class="profile-container">
  <%= @user.name %><br>
  <%= link_to "View my profile", @user %><br>
    <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
    <%= @user.followed_users.count %>
    </strong>
    following
    </a>
    <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
    <%= @user.followers.count %>
    </strong>
    followers
    </a>
    <br>
    Posts: <%= current_user.notes.count %><br>
    Average Savings: <%= number_to_percentage total_average.ceil, precision: 0 %>
  

  <h4>Add a note:</h4>
  <%= form_for @note, id: "note-form" do |f| %>
    <%= f.text_area :content, placeholder: "Add a new note...", rows: 1, id: "txtComment" %><br>
    <div class="note-btn">
      <%= f.submit "Add Note", class: "btn btn-small btn-primary enableOnInput", id: "note-dis", disabled: "disabled" %>
      &nbsp;&nbsp;&nbsp;<span class="counter"></span>

    </div>
  <% end %>
  
</div>
</div>

<div class="side-box-container">
  <div class="box-header">
    <p class="box-header-text">My Lists | <span id="add-list-link">Add List</span>
    </p>
  </div>
  
  
  <div class="add-list">
    <%= form_for @list, html: { class: "form-inline" } do |f| %>
      <%= f.text_field :name, placeholder: "List", class: "input-medium" %>
      <a class="close" href="#" id="close-add-list">&times;</a>
      <%= f.submit "Add", class: "btn" %>
    <% end %>
  </div>


  <div class="shopping-lists-container">
  <% for list in @shopping_lists %>
  <% if @shopping_lists.present? %> 
    <% if list.items.count > 1 %>
    <p>
      <%= link_to list.name, list %> (<%= list.items.count %> <%= "Item".pluralize %>)
      <%= link_to "Edit", list, class: "lite-link" %>
    </p> 
    <% elsif list.items.count == 1 %>
    <p>
      <%= link_to list.name, list %> (<%= list.items.count %> Item)
      <%= link_to "Edit", list, class: "lite-link" %>
    </p>
    <% elsif list.items.count == 0 %>
    <p>
      <%= link_to list.name, list %> (<%= list.items.count %> <%= "Item".pluralize %>)
      <%= link_to "Edit", list, class: "lite-link" %>
    </p>
    <% end %>
  <% else %>
  <p>You currently have no shopping lists created.</p>
  <% end %>
  <% end %>


  <!-- WORKING ON REMOTE GROCERY LISTS -->


  </div>
</div>


<div class="side-box-container">

  <div class="box-header">
    <p class="box-header-text">Quick Links | <span id="add-link">Add Link</span></p>
  </div>
  
  <div class="add-link-container">
    <%= form_for @link, html: { class: "form-inline" } do |f| %>
      <%= f.text_field :link_name, placeholder: "Link Name", class: "input-medium" %>
      <a class="close" href="#" id="close-add-link">&times;</a>
      <%= f.text_field :link_url, placeholder: "URL", class: "input-medium" %>

      <br>
      <%= f.submit "Add Link", class: "btn" %>
    <% end %>
  </div> 
  <div class="links-container">
  <% for link in @link_list %>
    <p><%= link_to link.link_name, link.link_url, target: "_blank" %></p>
  <% end %>
  </div>
</div>
</div>

bogoapp/app/views/pages/home.html.erb
<% if user_signed_in? %>
<% @user ||= current_user %>
<div class="alt-pg-container">
  <%= render "header_logged_in" %>
  
  <div class="container-narrow">
    <div class="alt-profile-container-top">
      <div class="row-fluid">
        <div class="span6">
          <%= image_tag "bogologo.jpg", class: "profile-img" %>
          <h3><%= current_user.name %></h3>
          <p class="town">Spring Hill, TN</p>
        </div>
        <div class="span6">
          <ul class="inline pull-right">
            <li>
              <div class="profile-list-borderless">
                <h3 class=""><%= current_user.notes.count %></h3>
                <p>Notes</p>
              </div>
            </li>
            <li>
              <div class="profile-list">
                <h3><%= @user.followed_users.count %></h3>
                <p>Following</p>
              </div>
            </li>
            <li>
              <div class="profile-list">
                <h3><%= @user.followers.count %></h3>
                <p>Followers</p>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="alt-profile-container-bottom">
      <div class="row-fluid">
        <div class="span8">
          <%= form_for @note, id: "note-form" do |f| %>
            <%= f.text_area :content, placeholder: "Add a note...", rows: 3, id: "noteContent", class: "input-block-level" %>
          <div class="note-submit">
            <%= f.submit "Add Note", class: "note-green-btn enableOnInput", id: "note-dis", disabled: "disabled" %> &nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Shorten your links with bitly.com", "https://bitly.com", class: "cancel", target: "_blank" %>
            <span class="counter pull-right count-number"></span>
          </div>
          <% end %>
        </div>
        <div class="span4 savings">
          <p>Average Savings:</p>
          <% if @recent_transactions.blank? %>
          <h3>0%</h3>
          <% else %>
          <h3><%= number_to_percentage total_average.ceil, precision: 0 %></h3>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container-narrow">
    <div class="row-fluid">
      <div class="span4">
        <div class="alt-dashbox">
          <div class="alt-dashbox-title">
            <div class="row-fluid">
              <div class="span8">
                <h4>Shopping Lists</h4>
              </div>
              <div class="span4 dropdown arrow-right">
                <a class="dropdown-toggle add-button pull-right" data-toggle="dropdown" href="#"><i class="icon-plus"></i></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                <li>
                  <div class="dropdown1-container">
                    <%= form_for @list, html: { class: "form-inline", id: "list-form" } do |f| %>
                      <div class="list-input">
                        <label>List Name</label>
                        <%= f.text_field :name, placeholder: "List Name" %>
                      </div>
                      <div class="submit-container">
                        <%= f.submit "Add List", class: "note-green-btn" %><span class="pull-right cancel-link"><%= link_to "Cancel", "#", class: "cancel" %></span>
                      </div>
                    <% end %>
                  </div>
                </li>
              </ul>
              </div>
            </div>    
          </div>
          <div class="alt-shopping-list-container">
            <ul>
            <% for list in @shopping_lists %>
              <% if list.items.count > 1 %>
                <li>
                <%= link_to list.name, list, class: "dark-link" %>
                <span class="item-count">(<%= list.items.count %> <%= "Item".pluralize %>)</span>
                <span class="pull-right">
                  <%= link_to list, method: :delete do %>
                    <i class="icon-remove gray"></i>
                  <% end %>
                </span>
              </li>
              <% elsif list.items.count == 1 %>
                <li>
                <%= link_to list.name, list, class: "dark-link" %>
                <span class="item-count">(<%= list.items.count %> Item)</span>
                <span class="pull-right">
                  <%= link_to list, method: :delete do %>
                    <i class="icon-remove gray"></i>
                  <% end %>
                </span>
              </li>
              <% elsif list.items.count == 0 %>
                <li>
                <%= link_to list.name, list, class: "dark-link" %>
                <span class="item-count">(<%= list.items.count %> <%= "Item".pluralize %>)</span>
                <span class="pull-right">
                  <%= link_to list, method: :delete do %>
                    <i class="icon-remove gray"></i>
                  <% end %>
                </span>
              </li> 
              <% end %>
              
            <% end %>
            </ul>
          </div>
        </div>
        <div class="alt-dashbox">
          <div class="alt-dashbox-title">
            <div class="row-fluid">
              <div class="span8">
                <h4>Quick Links</h4>
              </div>
              <div class="span4 dropdown arrow-right">
                <a class="dropdown-toggle add-button pull-right" data-toggle="dropdown" href="#"><i class="icon-plus"></i></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <li>
                    <div class="dropdown1-container">
                      <%= form_for @link, html: { class: "form-inline", id: "list-form" } do |f| %>
                      <div class="list-input">
                        <label>Link Name</label>
                        <%= f.text_field :link_name, placeholder: "Link Name" %>
                      </div>
                      <div class="list-input">
                        <label>Link URL</label>
                        <%= f.text_field :link_url, placeholder: "http://example.com" %>
                      </div>
                      <div class="submit-container">
                        <%= f.submit "Add Link", class: "note-green-btn" %>
                        <span class="pull-right cancel-link"><%= link_to "Cancel", "#", class: "cancel" %>
                        </span>
                      </div>
                      <% end %>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div class="alt-quick-link-container">
            <ul>
            <% for link in @link_list %>
              <li>
                <%= link_to link.link_name, link.link_url, target: "_blank", class: "dark-link" %>
                <span class="pull-right">
                  <%= link_to link, method: :delete do %>
                    <i class="icon-remove gray"></i>
                  <% end %>
                </span>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="span8">
        <div class="alt-dashbox">
          <div class="alt-dashbox-title">
            <div class="row-fluid">
              <div class="span8">
                <h4>Recent Transactions</h4>
              </div>
              <div class="span4 dropdown arrow-right">
                <a class="dropdown-toggle add-button pull-right" data-toggle="dropdown" href="#"><i class="icon-plus"></i></a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                  <li>
                    <div class="dropdown1-container">
                      <%= form_for @transaction, html: {id: "list-form"} do |f| %>
                        <div class="list-input input-prepend">
                          <label>Transaction Date</label>
                          <div class="input-prepend">
                            <span class="add-on"><i class="icon-calendar"></i></span>
                            <%= f.text_field :date, id: "datepicker", placeholder: "Date" %>
                          </div>
                        </div>
                        <div class="list-input">
                          <label>Amount Spent</label>
                          <div class="input-prepend">
                            <span class="add-on">$</span>
                            <%= f.text_field :spent, placeholder: "Spent" %>
                          </div>
                        </div>
                        <div class="list-input input-prepend">
                          <label>Amount Saved</label>
                          <div class="input-prepend">
                            <span class="add-on">$</span>
                            <%= f.text_field :saved, placeholder: "Saved" %>
                          </div>
                        </div>
                        <div class="submit-container">
                          <%= f.submit "Add Transaction", class: "note-green-btn" %><span class="pull-right cancel-link"><%= link_to "Cancel", "#", class: "cancel" %></span>
                        </div>
                      <% end %>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div class="alt-recent-transaction-list">
            <ul>
            <% for transaction in @recent_transactions %>
              <li>
                You spent <span class="transaction-list-bold"><%= number_to_currency transaction.spent %></span> at Piggly Wiggly on <%= transaction.date.strftime("%b %-d") %> and saved <span class="transaction-list-bold"><%= number_to_currency transaction.saved %></span> (<span class="transaction-list-green"><%= number_to_percentage transaction.average_savings_per_transaction.ceil, precision: 0 %></span>).
              </li>
            <% end %>
            </ul>
            <% if @recent_transactions.present? %>
            <div class="transaction-all">
              <p><%= link_to "View all transactions", "#", class: "green-link" %></p>
            </div>
            <% end %>
          </div>
        </div>
        <div class="alt-dashbox">
          <div class="alt-dashbox-title">
            <h4>Recent Activity</h4>
          </div>
          <div class="alt-activity-container">
            <!-- RECENT ACTIVITY FEED -->
            <% for note in @home_feed %>
            <div class="alt-note-container">
              <div class="row-fluid">
                <div class="span1">
                  <%= image_tag "bogologo.jpg", size: "40x40" %>
                </div>
                <div class="span11 recent-note">
                  <h5>
                    <%= link_to note.user.name, user_path(@user), class: "note-name" %>
                    <span class="pull-right gray-time"><%= time_ago_in_words(note.created_at) %></span>
                  </h5>
                    <p class="text"><%= note.content %></p>
                    <div class="note-nav">
                      <% if note.user == current_user %>
                      <span class="gray"><%= link_to(raw('<i class="icon-trash"></i> Delete'), "#", class: "dark-link") %></span>
                      <% else %>
                      <span class="gray"><i class="icon-share-alt"></i> Reply</span>
                      <span class="icon-pad"></span>
                      <% end %>
                    </div>
                </div>
              </div>
            </div>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% else %>
<div class="alt-pg-container">
<%= render "header_logged_out" %>
<h3>You need to login!</h3>
</div>
<% end %>

bogoapp/app/views/pages/sign_in.html.erb
<div class="signup-form-container">
	<div class="sign-up-top">
    <h3>Sign in to your Bogofy account.<a class="close" href="/">&times;</a></h3>
    <p>Don't have an account? <%= link_to "Sign up for FREE!", new_account_path, class: "green-link" %></p>
  </div>
  <div class="sign-up-bottom">
  	<%= form_tag "/auth/identity/callback", class: "form-horizontal", autocomplete: "off" do %>
      <% if @identity && @identity.errors.any? %>
      <div class="error_messages">
        <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
        <ul>
          <% @identity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <div class="control-group">
        <label class="control-label">Email</label>
        <div class="controls">
          <%= text_field_tag :auth_key %>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="inputEmail">Password</label>
        <div class="controls">
          <%= password_field_tag :password %>
        </div>
      </div>
      
      <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
          
          <div class="signin-submit">
            <%= submit_tag "Sign In", class: "note-green-btn" %>
            <span class="or">or</span>
            <%= link_to "Sign in with Facebook", "/auth/facebook", class: "signin-fb-btn" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>