bogoapp/config/routes.rb
Bogoapp::Application.routes.draw do

  resources :blogs

  

  resources :administrators

  resources :categories

  
  

  match "posts/category" => "posts#category"
  resources :posts

  resources :links

  resources :lists do
    resources :items
  end
  

  resources :transactions

  resources :notes
  match "tutorials", to: "pages#tutorials", as: "tutorials"
  match "terms-of-service", to: "pages#terms_of_service", as: "terms"
  get "pages/sign_in"
  match 'sign-in', to: 'pages#sign_in', as: 'sign_in'
  get "pages/home_alt"
  get "users/show"

  match 'sign-up', to: 'identities#new', as: 'new_account'
  resources :identities

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  

  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end
  root to: "pages#home"
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  mount RedactorRails::Engine => '/redactor_rails'

end

bogoapp/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

bogoapp/app/models/administrator.rb
class Administrator < ActiveRecord::Base
  attr_accessible :name

end

bogoapp/app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :name

  has_many :posts
end

bogoapp/app/models/categorization.rb
class Categorization < ActiveRecord::Base
  attr_accessible :category_id, :post_id

  belongs_to :post
  belongs_to :category
end

bogoapp/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :categorizations
  has_many :posts, through: :categorizations

  validates_presence_of :name
  validates_uniqueness_of :name
  
end

bogoapp/app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  attr_accessible :email, :name, :password, :password_confirmation#, :password_digest
  
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i

end

bogoapp/app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :completed, :list_id, :name

  belongs_to :list

end

bogoapp/app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :link_name, :link_url, :user_id

  belongs_to :user
end

bogoapp/app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :user_id

  belongs_to :user
  has_many :items

  
end

bogoapp/app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :content, :user_id

  belongs_to :user
  validates_presence_of :content

  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", 
          user_id: user.id)
  end
end

bogoapp/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :publish_on, :published, :status, :title, :category_ids, :author, :blog_id

  has_many :categorizations
  has_many :categories, through: :categorizations
  accepts_nested_attributes_for :categorizations
  belongs_to :blog

  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :body
  validates_presence_of :status

  def self.search(search)
  	if search
  		find(:all, conditions: ['title || body LIKE ?', "%#{search}%"])
  	else
  		find(:all)
  	end
  end
end

bogoapp/app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

bogoapp/app/models/transaction.rb
class Transaction < ActiveRecord::Base
  attr_accessible :date, :saved, :spent

  belongs_to :user

  def average_savings_per_transaction
  	total = self.spent + self.saved
  	average = self.saved / total * 100
  end

  
end

bogoapp/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid
  attr_accessor :password

  has_many :links
  has_many :lists
  has_many :transactions
  has_many :notes
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

  def following?(other_user)
  	relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
  	relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
  	relationships.find_by_followed_id(other_user.id).destroy
  end	

  def feed
    Note.from_users_followed_by(self)
  end


  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at) unless auth.credentials.expires_at.nil?
      user.save!
    end
  end
end

bogoapp/app/controllers/lists_controller.rb
class ListsController < ApplicationController
	def create
		@list = current_user.lists.build(params[:list])
		if @list.save
			redirect_to root_path
		end
	end

	def show
		@list = current_user.lists.find(params[:id])
		@item = @list.items.build
		@item_list = @list.items.order("created_at asc")

		@shopping_lists = current_user.lists.order("name asc")
		@link_list = current_user.links.order("link_name asc")

		respond_to do |format|
			format.html
			format.pdf do
				pdf = ListPdf.new(@list)
				send_data pdf.render 
			end
		end
	end

	def destroy
		@list = current_user.lists.find(params[:id])
		@list.destroy
		redirect_to root_path
	end

	
end

bogoapp/app/helpers/blogs_helper.rb
module BlogsHelper
end

bogoapp/app/helpers/categories_helper.rb
module CategoriesHelper
end

bogoapp/app/helpers/items_helper.rb
module ItemsHelper
end

bogoapp/app/helpers/links_helper.rb
module LinksHelper
end

bogoapp/app/helpers/lists_helper.rb
module ListsHelper
end

bogoapp/app/helpers/notes_helper.rb
module NotesHelper
end

bogoapp/app/helpers/sessions_helper.rb
module SessionsHelper

	def current_user?(user)
    user == current_user
  end
  
end

bogoapp/app/helpers/users_helper.rb
module UsersHelper
end

bogoapp/app/views/lists/show.html.erb
<% @user ||= current_user %>

<div class="alt-pg-container">
  <%= render "pages/header_logged_in" %>

  <div class="container-narrow">
    <div class="alt-profile-container-1">
      <div class="row-fluid">
        <div class="span6">
          <%= image_tag "bogologo.jpg", class: "profile-img" %>
          <h3><%= current_user.name %></h3>
          <p class="town">Spring Hill, TN</p>
        </div>
        <div class="span6">
          <ul class="inline pull-right">
            <li>
              <div class="profile-list-borderless">
                <h3 class=""><%= current_user.notes.count %></h3>
                <p>Notes</p>
              </div>
            </li>
            <li>
              <div class="profile-list">
                <h3><%= @user.followed_users.count %></h3>
                <p>Following</p>
              </div>
            </li>
            <li>
              <div class="profile-list">
                <h3><%= @user.followers.count %></h3>
                <p>Followers</p>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <div class="container-narrow">
    <div class="row-fluid">
      <div class="span4">
        <div class="alt-dashbox">
          <div class="alt-dashbox-title">
            <h4>Shopping Lists</h4>
          </div>
          <div id="shopping-list-show-pg" class="alt-shopping-list-container">
            <%= render "items/show_list" %>
          </div>
        </div>
        <div class="alt-dashbox">
          <div class="alt-dashbox-title">
            <h4>Quick Links</h4>
          </div>
          <div class="alt-quick-link-container">
            <ul>
            <% for link in @link_list %>
              <li>
                <%= link_to link.link_name, link.link_url, target: "_blank", class: "dark-link" %>
                <span class="pull-right">
                  <%= link_to link, method: :delete do %>
                    <i class="icon-remove gray"></i>
                  <% end %>
                </span>
              </li>
            <% end %>
            </ul>
          </div>
        </div>

      </div>
      <div class="span8">
        <div class="alt-dashbox-1">
          <div class="alt-dashbox-title-1">

            <h2><%= @list.name %></h2>

          </div>
          <div class="alt-shopping-list-items">
            <div class="export-container">
              <div class="pull-right icon-tab">
                <%= link_to(list_path(@list, format: "pdf"), class: "pdf") do %>
                <i class="icon-print"></i>
                <% end %>
              </div>
              
              <div class="pull-right icon-tab">  
                <i class="icon-envelope"></i>
              </div>
            </div>

            <%= form_for([@list, @list.items.build], remote: true) do |f| %>
              <div class="item-list-input">
                <%= f.text_field :name, placeholder: "Add item...", class: "input-block-level lister", autofocus: true, autocomplete: "off" %>
              </div>
              <div class="hide-submit">
                <%= f.submit "Add Item", class: "note-green-btn" %>
              </div>
            <% end %>
            <div id="items" class="items-list-con">
              <ul>
                <%= render @list.items %>
              </ul>
            </div>
            <div id="print-code">
              <p><%= link_to "Printable Shopping List (PDF)", list_path(@list, format: "pdf") %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



</div>

bogoapp/app/views/lists/show_alt.html.erb
<% @user ||= current_user %>
<div class="hm-header">
  <div class="container-narrow">
    <h4><%= link_to_unless_current "Home", root_path %> | <%= link_to "Profile", current_user %> | <%= link_to "Sign out", signout_path, id: "sign_out" %></h4>
  </div>
</div>
<div class="container-narrow">
  <div class="row-fluid">
    <div class="span4">

      <div class="side-box-container">
        <%= @user.name %><br>
        <%= link_to "View my profile", @user %><br>
        <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
        <%= @user.followed_users.count %>
        </strong>
        following
        </a>
        <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
        <%= @user.followers.count %>
        </strong>
        followers
        </a>
        <br>
        Posts: <%= current_user.notes.count %><br>
        Average Savings: <%= number_to_percentage total_average.ceil, precision: 0 %>
      </div>
      
      <div class="side-box-container">
        <div class="box-header">
          <p class="box-header-text">My Lists | <span id="add-list-link">Add List</span></p>
        </div>
  
  
        <div class="add-list">
          <%= form_for @list, html: { class: "form-inline" } do |f| %>
          <%= f.text_field :name, placeholder: "List", class: "input-medium" %>
          <%= f.submit "Add List", class: "btn" %>
          <% end %>
        </div>


        <div class="shopping-lists-container">
          <% for list in @shopping_lists %>
            <% if @shopping_lists.present? %> 
            <% if list.items.count > 1 %>
            <p>
              <%= link_to list.name, list %> (<%= list.items.count %> <%= "Item".pluralize %>)
              <%= link_to "Edit", "#", class: "lite-link" %>
            </p> 
            <% elsif list.items.count == 1 %>
            <p><%= link_to list.name, list %> (<%= list.items.count %> Item)</p>
            <% elsif list.items.count == 0 %>
            <p><%= link_to list.name, list %> (<%= list.items.count %> <%= "Item".pluralize %>        )</p>
            <% end %>
            <% else %>
            <p>You currently have no shopping lists created.</p>
            <% end %>
          <% end %>
        </div>
      </div>
      
      
    </div>
    <div class="span8">
    	<h3><%= @list.name %></h3>

    	<%= form_for([@list, @list.items.build], remote: true) do |f| %>
    		<%= f.text_field :name, placeholder: "Add item...", class: "input-xxlarge" %><br>
    		<%= f.submit "Add Item", class: "btn" %>
    	<% end %>

      <div id="items">
        <%= render @list.items %>
      </div>
    </div>
  </div>
</div>